### ISSUE TITLE
Preprocessing of the MASS dataset

### ISSUE THREAD

**Issue by MathieuSeraphim** [gist-ailab/IITNet-official#1]
Hello,

I would like to use your program with the MASS dataset, to which I have access.
Unfortunately, I do not see how the file prepare_physionet.py  could be called to parse said dataset.

The files in the dataset as I have it follow this format:
01-03-0001 Annotations.edf
01-03-0001 Base.edf
01-03-0001 PSG.edf
01-03-0002 Annotations.edf
... etc.

They are not properly parsed by prepare_physionet.py. For instance, they do not include any field for an electrode F4-EOG.

I could probably retro-engineer your process to an extent in order to make the preprocessing work, but as I wish to reproduce your results, I am weary of potentially making a mistake. (For instance, I could reproduce the F4-EOG signal from the available F4 and EOG signals, but as there are two EOG signals in MASS, I'd have to make an arbitrary choice...)

Could you please share the script you used to generate the preprocessed MASS data?

Thank you in advance.

**Comment by SeongjuLee** [comment]
Thank you for leaving issue.
There are two types of EOG channels; left and right
As mentioned in the paper, we used left EOG channel in our work.
To get F4-EOG signal, we extract F4 channel and left EOG channel from EDF file.
Then, we substracted EOG from F4 (superposition F4 and minus EOG).

I'll update the script of processing MASS as soon as possible.

**Comment by MathieuSeraphim** [comment]
Thank you very much!
Would it also be possible to include the config files for MASS?
Thanks in advance!

**Comment by kyoobinlee** [comment]
http://ceams-carsm.ca/mass/
Thanks.
